### ISSUE TITLE
Please set the Java Tool chain in core/build.gradle

### ISSUE THREAD

**Issue by manticore-projects** [JetBrains/jediterm#274]
core/build.gradle:
```groovy
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of('11))
    }
}
```

**Comment by manticore-projects** [comment]
Also the Java Samples are misleading now.
Only the Kotlin JeditMain App works correctly on Linux + Java.

Would you like to receive a PR on both issues?

**Comment by segrey** [comment]
@manticore-projects Thanks for spotting this. Fixed by https://github.com/JetBrains/jediterm/commit/8372a7fda868edf530c0873755fbc92e59657a00

As for the Java Samples, I've just checked it on Windows and both `com.jediterm.example.BasicTerminalExample` / `com.jediterm.example.BasicTerminalShellExample` work for me. Could you please describe your problem with samples in a new issue first? (Yes, PR are always welcome.)

**Comment by segrey** [comment]
Closed as fixed

**Comment by manticore-projects** [comment]
What I meant is:

1) the Kotlin Std. lib needs to be included, else the Resizing does not work (although there is no error message).

2) you deprecated some code which I found from the Kotlin example. But the Java example still shows the old, deprecated code.

**Comment by segrey** [comment]
1. Yes, `kotlin-stdlib:1.9.0` should be included by clients. Usually, it happens automatically as jediterm-core exposes its runtime dependencies in pom.xml.
2. If you meant [UIUtil](https://github.com/JetBrains/jediterm/blob/a7670d96cfc65e49f5214750ec5259ca5a9f49eb/JediTerm/src/main/java/com/jediterm/example/BasicTerminalShellExample.java#L32), I will update its usages, thanks for spotting. If it's something else, please share a link to deprecated code usage.

**Comment by manticore-projects** [comment]
> 1. Yes, `kotlin-stdlib:1.9.0` should be included by clients. Usually, it happens automatically as jediterm-core exposes its runtime dependencies in pom.xml.

Correct, but this works only recently with the Maven Artifact.
Before I had to copy/link the local libraries and I skipped most (JNA, Logger etc.) because I had those in my own dependencies already.

Basically it's all about my bias: I though Kotlin compiles into Java Class and so would not be needed for the JAR files.
But since you are converting to Kotlin now, this assumption does not hold.

>     2. If you meant [UIUtil](https://github.com/JetBrains/jediterm/blob/a7670d96cfc65e49f5214750ec5259ca5a9f49eb/JediTerm/src/main/java/com/jediterm/example/BasicTerminalShellExample.java#L32), I will update its usages, thanks for spotting. If it's something else, please share a link to deprecated code usage.

Yes, this one exactly.

Thank you a lot for helping! Cheers!
